"""Challenge type, reward

Revision ID: 11bc3a2a1e87
Revises: 6d2c5a701d58
Create Date: 2023-10-12 14:07:56.906976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11bc3a2a1e87'
down_revision = '6d2c5a701d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenge_type', sa.Enum('daily', 'weekly', 'monthly'), nullable=False))
        batch_op.add_column(sa.Column('reward', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('reward')
        batch_op.drop_column('challenge_type')

    # ### end Alembic commands ###
